title: "NeuroLogicX Research"
email: "abhishekt282001@gmail.com"
description: "A Modular Neurosymbolic Framework for General-Purpose Reasoning"
baseurl: "/neurologicx_terminal"  # This must match your repo name!
url: "https://abhishek282001tiwari.github.io"
github_username: "Abhishek282001Tiwari"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

research_paper_url: "https://www.techrxiv.org/users/942678/articles/1316379"
streamlit_app_url: "https://neurologicx.streamlit.app"
github_repo: "https://github.com/Abhishek282001Tiwari/NeuroLogicX"

# Navigation
header_pages:
  - index.md
  - research.md
  - demo.md
  - results.md
  - paper.md
  - about.md

# Build settings
safe: false